### ISSUE TITLE
Check if JSON is valid, and report

### ISSUE THREAD

**Issue by madpipeline** [code4romania/date-la-zi#188]
The Parser service should check if the JSON is valid and report an error. Do not write the JSON to S3 if it's not valid.

The API service should check if the JSON is valid and output to logs proper error message describing the issue. Also it should return an error message to API REST requests regarding broken data.

**Comment by chalx** [comment]
Hello, am facut un check legat de ceea ce ai zis mai sus si vad ca validarea se face atunci cand se apeleaza acel endpoint si incearca sa faca conversie la un obiect de tip `DailyPdfStats`.

Rezultatul pentru urmatorul input:
```json
{ "name": "asdasd}
```

Output

![image](https://user-images.githubusercontent.com/4411836/77804733-ecdd2300-7088-11ea-8751-f8668b5a72b6.png)

Sper ca la asta te referi.

**Comment by theodorjurubita** [comment]
Hey, I can take a look at it. 
Cheers!

**Comment by madpipeline** [comment]
The issue asks for logs on the error, in order to track down the issue in deployment.

If you started working on this, please assign yourself to it.

**Comment by theodorjurubita** [comment]
I don't think I have rights, or am I missing something?
I don't see how I can assign myself.

**Comment by CristiHabliuc** [comment]
@theodorjurubita it looks like someone else is already investigating the issue. Let's see where we stand with it first. Thanks for looking into it!

**Comment by theodorjurubita** [comment]
Ok, np. I can look at something else. I haven't made the setup yet anyway :P.

**Comment by CristiHabliuc** [comment]
@chalx please see this answer:

> The issue asks for logs on the error, in order to track down the issue in deployment.

**Comment by CristiHabliuc** [comment]
> Ok, np. I can look at something else. I haven't made the setup yet anyway :P.

Awesome, let us know if you need assistance

**Comment by Utwo** [comment]
This is not needed anymore since the project it's pure frontend static now. :smiley_cat:
