### ISSUE TITLE
Add  distributed cache for latest data

### ISSUE THREAD

**Issue by idormenco** [code4romania/date-la-zi#19]
Create derived type from `ICacheSercice` and implement it's members which you think are relevant .
Use `CacheOptions` and `appsettings` to configure cache (cachelocation,lifespan etc)

**Comment by GabrielMajeri** [comment]
I want to work on this issue. Could you give me some pointers as to where I can start adding the cache functionality?

**Comment by idormenco** [comment]
@RaduCStefanescu @bvizureanu do we need here distributed cache, if so ,what solution should we use ?

**Comment by CristiHabliuc** [comment]
I think we already handled this via cloudfront. Right, @andreiio ?

**Comment by andreiio** [comment]
@CristiHabliuc no, we rolled it back because the deployment ended up being stable.

**Comment by Utwo** [comment]
This is not needed anymore since the project it's pure frontend static now. :smiley_cat:
