### ISSUE TITLE
Parser and API relationship

### ISSUE THREAD

**Issue by madpipeline** [code4romania/date-la-zi#23]
# Story

As a Health Ministry representative I want to be able to upload the excel to the `Date La Zi` platform from a dedicated page and have the data in the platform be updated,

# Implementation proposal

* The Backend(API) and Parser applications to run and behave as services callable via a REST API
* The Backend to present an upload endpoint to receive an MS Excel file, which will send the file with the proper parameters ti the Parser service
* The Parser service to respond to the request with the converted JSON
* The Backend to validate the received JSON, apply any needed changes and update the DB with the JSON data.

# Acceptance criteria

* Single user facing application
* Dedicated user role that gives the Excel upload permission

**Comment by pringon** [comment]
Me and https://github.com/alexxozo will take this one :)

**Comment by idormenco** [comment]
@pringon i don't think this flow was approved . can you please discuss it with @RaduCStefanescu

**Comment by chalx** [comment]
@idormenco poti sa adaugi un lable care sa indice faptul ca inca nu e gata de implementare?

**Comment by RaduCStefanescu** [comment]
This issue is not needed at the moment.
The parser is not part of the setup at this time.
