### ISSUE TITLE
Daily data table

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/date-la-zi#245]
We need to create a table that will use the same data as the daily chart and have the following info:

- date
- infection count
- healed count
- death count

This table should also have pagination and limit the number of rows to a reasonable amount.

**Comment by chalx** [comment]
@CristiHabliuc paginarea nu poate fi facuta decat in memorie, din cate vad nu avem un API cu paginare pentru datele respective (sau poate ma insel eu) asa ca in loc de paginare sa limitam tabelul la o anumita dimensiune si dupa sa afisam cu scroll toate datele?

**Comment by CristiHabliuc** [comment]
@chalx cred ca paginare in memorie e perfect pentru situatia asta. Posibil in viitor sa aplicam filtre (deocamdata nu sunt multe date). Scroll in container nu cred ca e o solutie. 

Poti face paginarea in-mem? 

Motivul principal pentru cardul acesta e sa vedem desfasurat cifrele pentru bar chartul pe zile, pe masura ce vor creste numarul zilelor

**Comment by cipas** [comment]
@CristiHabliuc vad un PR aici, se ocupa cineva de issue sau e liber ?

**Comment by CristiHabliuc** [comment]
Da, se ocupa @chalx de el. Teoretic e aproape gata, sunt niste issues cu GHA pentru care asteptam confirmare
