### ISSUE TITLE
Refactor footer to use taskforce-fe-components Footer components

### ISSUE THREAD

**Issue by pdamoc** [code4romania/date-la-zi#255]
The current footer reimplements the functionality already present in the [Footer component](https://taskforce-fe-components.now.sh/?path=/story/footer--with-one-column) and has problems displaying on mobile.

**Comment by CristiHabliuc** [comment]
Great idea @pdamoc ! I think it wasn't finished in time for the release. Do you have time to take it on?

**Comment by CristiHabliuc** [comment]
I would add that the components are already added to the project and the `Instruments` component is already implemented (visible in the Dashboard page). The dependency might need a version bump tho, I'm not sure.

**Comment by pdamoc** [comment]
I will focus on this as soon as I finish what I'm currently working on.

**Comment by CristiHabliuc** [comment]
Appreciate it! 🙏

**Comment by danichim** [comment]
Can I take this?

**Comment by CristiHabliuc** [comment]
Sure, if you have the time. @pdamoc is that okay?

**Comment by pdamoc** [comment]
Go for it @danichim !
