### ISSUE TITLE
Daily table shows the current day twice

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/date-la-zi#265]

**Comment by andorremus** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/9131872/77847393-69751c00-71c5-11ea-8d96-16776ad33bd2.png">

Problema pare sa fie de la back-end, datele sunt aratate corect dar ultima zi e de fapt un total al tuturor celorlalte zile

**Comment by idormenco** [comment]
on it. @andorremus acel state e creat pe client si nu backend

**Comment by andorremus** [comment]
ok, @idormenco I can have a look if you have other stuff to do

**Comment by idormenco** [comment]
@andorremus sorry but i think i already fixed it :( you can review my pr

**Comment by andorremus** [comment]
well done @idormenco  :) ma pun sa vanez altele acum
