### ISSUE TITLE
Add county data to API endpoint

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/date-la-zi#277]
They should be in a separate key inside the `/ui-data` response. Let's use the county codes if we have them so we don't have to worry about diacritics.

The response would ideally be a hashmap like this:

```
...
"counties": {
  "is": 24,
  "b": 300,
  "sv": 900,
  ...
}
...
```

**Comment by idormenco** [comment]
Api provides this response and uses ISO found here https://en.wikipedia.org/wiki/Counties_of_Romania
