### ISSUE TITLE
Add last_update date to groups in API

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/date-la-zi#278]
Each group of the api response should also have an optional `last_updated_on` field (a timestamp) that, if specified, will be shown in the interface as the last time that chart was updated.

Again, it should be optional. Its lack means it will not be displayed (so that we won't have to edit this all the time, making this more error prone).

**Comment by CristiHabliuc** [comment]
LE: I noticed the response already has this field, it looks like it's the same as the one edited at time of JSON. But we should only show it if it was set for a specific part of data (some charts will have it, other not)

**Comment by idormenco** [comment]
on it
