### ISSUE TITLE
Implement stale state for some charts

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/date-la-zi#279]
Some charts might not get data as frequent as they should, so we need a way to tell the viewer the data is stale. We'll do this by showing the last updated time (if the API specifies it, [read the details here](https://github.com/code4romania/date-la-zi/issues/278)).

If that timestamp is missing from the response group, don't show it at all.

Ideally it would be shown next to the title (or somewhere it fits nicely and doesn't break the layout)

**Comment by Utwo** [comment]
me

**Comment by Utwo** [comment]
#284

**Comment by Utwo** [comment]
This can be closed
