### ISSUE TITLE
Re-enable the county map

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/date-la-zi#280]
Since we now have county information again, let's add the county map back (it's already built, the `CountiesCard` component).

- [ ] Also enable the embed options for it, see other cards about how it's done

**Comment by Utwo** [comment]
I take this

**Comment by CristiHabliuc** [comment]
@Utwo have you made any progress on this one? I can take it off your hands if not

**Comment by Utwo** [comment]
It's included in #284

**Comment by Utwo** [comment]
This can be closed
