### ISSUE TITLE
Counties names cross counties' borders in many cases

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/date-la-zi#286]
A lot of counties' names cross their borders so I think it's best to hide the labels

```
emphasis: {
    label: {
        show: false
    }
},
```

![image (6)](https://user-images.githubusercontent.com/2820084/78369100-5602f000-75cd-11ea-83cb-a73226c64e7d.png)
![image (5)](https://user-images.githubusercontent.com/2820084/78369102-569b8680-75cd-11ea-9214-69b7c1be838e.png)

Looking at an [echarts example with the map of USA](https://www.echartsjs.com/examples/en/editor.html?c=map-usa) setting `emphasis.label.show` on false should solve this

**Comment by tudorgergely** [comment]
if this still relevant? since #284 got merged and it seems to hide the labels

**Comment by tudoramariei** [comment]
True, I forgot to link the issues beforehand
Closing this now
