### ISSUE TITLE
Create component for total confirmed cases

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/date-la-zi#287]
I believe we need to increase the scale of the current _total number of cases_. The component should be similar in size to the existing `numar de cazuri pe zile` component in order to properly show the exponential increase

The current visualisation used for confirmed cases is misleading since it doesn't show the true situation in the country. The growth per each day is **exponential**, though the graphic seems to only be growing ever so slightly

![image](https://user-images.githubusercontent.com/2820084/78371395-93b54800-75d0-11ea-990e-af71fe63061b.png)

This same effect can be seen on the [JHU graphics](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) if the confirmed cases graphic's size is distorted as shown below 

![image](https://user-images.githubusercontent.com/2820084/78371232-59e44180-75d0-11ea-9b56-f6c4ddc0488a.png)
_This is the same graphic, but with different dimensions_

**Comment by cipick** [comment]
i can take this if that's ok :)
