### ISSUE TITLE
Detected by browser and only show one component that shows the link to the extension

### ISSUE THREAD

**Issue by grigore-fiodorov** [code4romania/date-la-zi#300]
![image](https://user-images.githubusercontent.com/16736593/78557918-5e9c3600-781a-11ea-8a7e-5d3fa298ab26.png)

**Comment by CristiHabliuc** [comment]
Hey there, thanks for the tip!
We're showing both links there mostly for awareness (I myself am using mostly Safari, Chrome is secondary, so imagine seeing the page with no button at all, I would never guess that I could still have this on Chrome).
