### ISSUE TITLE
Type error prevents loading web application

### ISSUE THREAD

**Issue by ralupopa** [code4romania/date-la-zi#338]
![image](https://user-images.githubusercontent.com/62647565/80801377-d01a9a80-8bb4-11ea-8dde-b9b4307c4bfb.png)

Console looks like this ^; Reproduced on Chrome 81, Windows 10

**Comment by catileptic** [comment]
There is a spike around 1pm (UTC+3) when the intense traffic sometimes brings the website down. We are working on a new infrastructure and will deploy it soon, so this will be solved.
