### ISSUE TITLE
Daily data by region

### ISSUE THREAD

**Issue by ngbusca** [code4romania/date-la-zi#342]
Are the historical .json that feed the dashboard available somewhere? I'm trying to avoid having to crawl the site daily. Thanks!

**Comment by catileptic** [comment]
Yes, [we have an API available](https://api1.datelazi.ro/swagger/index.html).

Closing this issue. Re-open it if there are further questions.

**Comment by ngbusca** [comment]
Exactly what I was looking for, thanks for the quick answer!

**Comment by ngbusca** [comment]
Is the API down? I haven't been able to query it lately...

**Comment by catileptic** [comment]
Can you try a `GET` on `https://datelazi.ro/latestData.json`?

**Comment by ngbusca** [comment]
Perfect, thanks!!
