### ISSUE TITLE
Data for May 18, 2020, has a bug

### ISSUE THREAD

**Issue by Anonymous-Coward** [code4romania/date-la-zi#346]
It says 0 deaths/ Official data says 1097 for May 17 and 1107 for May 18. That would be 10 deaths, instead of 0.

Couldn't find any other contact info on datelazi.ro to report this. Maybe adding a contact link there would be useful.

**Comment by catileptic** [comment]
1107 was the total number of deaths [announced on the 17th](https://stirioficiale.ro/informatii/informare-de-presa-17-mai-2020-ora-9-01pm).

**Comment by Anonymous-Coward** [comment]
Later that day, [the official announcement of the health ministry at 13:00](http://www.ms.ro/2020/05/17/buletin-informativ-17-05-2020/) stated otherwise.

The infos from the ministry of internal affairs for [May 17](https://www.mai.gov.ro/informare-covid-19-grupul-de-comunicare-strategica-17-mai-2020-ora-13-00/) and [May 18](https://www.mai.gov.ro/informare-covid-19-grupul-de-comunicare-strategica-18-mai-2020-ora-13-00/) also contain the same numbers. Maybe it's a bug in your upstream info source.

**Comment by catileptic** [comment]
Please take a very close look at the update I linked above. It was put out at 9 in the evening. The official announcement that you link to arrives at 1 in the afternoon, every day. 

In other words, at 1pm on the 17th, the death toll was at 1097. At 9pm, an update raised the toll to 1107. 

At 1pm on the 18th, the death toll was still at 1107. 

Just now, on the 18th, [an update was issued](https://stirioficiale.ro/informatii/informare-de-presa-18-mai-2020-ora-7-53pm) raising the toll to 1120.

**Comment by Anonymous-Coward** [comment]
Sorry, me sometimes stupid. I'm used almost exclusively to 24h time format, didn't notice the pm.

**Comment by catileptic** [comment]
Glad we sorted this out! :)
