### ISSUE TITLE
Add number of processed tests in a day to graph.

### ISSUE THREAD

**Issue by web-sys1** [code4romania/date-la-zi#349]
I suggest you to implement the feature regarding the number of **tests processed per day** as well as number of tested people _per capita_ to your website called [Date La Zi](https://datelazi.ro/).

It is important to understand this situation of coronavirus (COVID-19) pandemic in Romania.

![Screenshot - COVID-19 pandemic in Romania - testing process 1593269815133](https://user-images.githubusercontent.com/61905565/85925282-02d4cc80-b8a0-11ea-9e54-ee9d4e6c445b.png)

According to Wikipedia page _[per Statistics section](https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Romania#Statistics)_, **total tested**, **no. of new tests** and _**7-day average of tests per day**_ would look same.

**Comment by catileptic** [comment]
Thank you for this suggestion! It is currently a feature request that we're also considering.

**Comment by web-sys1** [comment]
@catileptic Important to remind: number of tests (including retested persons). I may suggest addition regarding no. of people at Intensive care (ICM or ICU).

**Comment by web-sys1** [comment]
Hi @Utwo @andreiio here is another example (pics) about the graphs on number of tests per day & week average.
![Capture 025 - Testari Covid-19 pe zi in Romania - www graphs ro](https://user-images.githubusercontent.com/61905565/89438321-5e249500-d751-11ea-8cc1-2575b1b89be5.png)
![Capture 029 - Testari procentuale pozitive Covid-19 pe Saptamana - www graphs ro](https://user-images.githubusercontent.com/61905565/89438326-5f55c200-d751-11ea-969f-de3009067725.png)
![Capture 032 - Testari procentuale pozitive Covid-19 pe zi in Romania - www graphs ro](https://user-images.githubusercontent.com/61905565/89438329-6086ef00-d751-11ea-9d45-50a58bd937c2.png)
![Capture 037 - Teste defalcate SARS-CoV-2 - www graphs ro](https://user-images.githubusercontent.com/61905565/89438330-611f8580-d751-11ea-8893-1c37d0c3619f.png)

**Comment by catileptic** [comment]
i am closing this since it is not on our implementation roadmap
