### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by ngbusca** [code4romania/date-la-zi#350]
I'm getting a response 500 when querying the API:
```
import requests
r = requests.get('https://api1.datelazi.ro/api/v2/data')
r.status_code
500
```

**Comment by idormenco** [comment]
Hi @ngbusca api is no longer maintained ,to obtain data that is used on [date la zi ](https://datelazi.ro) please use this url [https://datelazi.ro/latestData.json](https://datelazi.ro/latestData.json)

**Comment by ngbusca** [comment]
great, thanks!
