### ISSUE TITLE
Graph not resizing when changing orientation

### ISSUE THREAD

**Issue by surdu** [code4romania/date-la-zi#351]
On mobile, when switching from portrait to landscape, the graphs do not resize.

Tested on Firefox for Android.

![Screenshot_20200713-142725](https://user-images.githubusercontent.com/11520795/87299697-2f7e1a80-c515-11ea-88a8-dbac5c647e45.jpg)

**Comment by web-sys1** [comment]
Is same issue? What the bug you encountered in the browser?

**Comment by surdu** [comment]
No. This reproduce on mobile phones when you change orientation

**Comment by catileptic** [comment]
this has been resolved, closing
