### ISSUE TITLE
Graph crashes if disabling one graph and then hover the graph

### ISSUE THREAD

**Issue by surdu** [code4romania/date-la-zi#361]
On the "Număr de cazuri pe zile" graph, if you disable one of the graphs by clicking on the legend of the graph, and then hover the graph, the graph will cease to work.

**Comment by catileptic** [comment]
I could not reproduce this on Chrome. Could you detail the steps? Also, what do you mean when you say the graph no longer works?

**Comment by surdu** [comment]
Sure thing!

Here is a GIF illustrating the issue (notice how the tooltip stops working and you also can't reactivate the disabled legend):

![Aug-05-2020 11-38-46](https://user-images.githubusercontent.com/11520795/89391097-614b6100-d710-11ea-8c6c-970ad57a56b6.gif)

**Comment by web-sys1** [comment]
Same there.
![screencapture-datelazi-ro-1596626060898](https://user-images.githubusercontent.com/61905565/89406613-189ea280-d726-11ea-8fe7-e7c08d1bab72.png)

**Comment by surdu** [comment]
@web-sys1 Looks like the same issue, or am I missing something ?

**Comment by web-sys1** [comment]
@surdu I would not miss this. There was an error while I was on website.

**Comment by web-sys1** [comment]
This scenario could happen, as it encountered error message .js file. It resulted **TypeError: Cannot read property 'seriesName' of undefined**
