### ISSUE TITLE
The section 'Cazuri confirmate pe judet' should be sorted by number, not by string

### ISSUE THREAD

**Issue by campanflaviu** [code4romania/date-la-zi#381]
Brasov county has the most cases in 1000 people but it's almost in the last place. This bug usually happens when sorting is done by string and not by number value.

![Screenshot 2020-09-21 at 09 20 42](https://user-images.githubusercontent.com/5280013/93737486-03a1a400-fbec-11ea-8010-008fd7dd014b.png)

**Comment by catileptic** [comment]
Thank you for bringing this up! We're on it
